### ISSUE TITLE
Create a Party (Renamed to Parties Collection)

### ISSUE THREAD

**Issue by amaalali** [crsanghani/street-party#2]
As a logged in user,
So that I can plan an event,
I want to be able to create a party.

- [ ] Add WebForm
- [x] Create new Mongo collection
- [ ] Add 'create party' button

**Comment by tomnunn** [comment]
Note: '/parties' route will display a list (or calendar/map view) of all parties from the DB.

**Comment by tomnunn** [comment]
Create as a New Issue, incomplete Feature due to the need for merging Party Schema into Master branch.
